name: ProxyPatternPool Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 3.13: gevent is not supported yet
        # 3.13: greenlet (eventlet?) is not supported yet
        # 3.13/3.14: TODO trigger nogil tests when available!
        # 3.13t 2024-11-28: broken rust interface for cryptography-cffi
        # 3.14t 2024-11-28: not supported
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "pypy3.10"]
    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      # FIXME cache: 'pip' # ???
      # uses: Quansight-Labs/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    # Dependencies
    - name: Install Python Dependencies
      run: |
        pip install -U pip
        pip install -e .[local,dev]
    # Checks
    - name: Check with pyright
      run: make VENV= check.pyright
    # - name: Check with black
    #  run: black --check ProxyPatternPool.py
    # - name: Check with flake8
    #   run: make VENV= check.flake8
    - name: Check with ruff
      run: make VENV= check.ruff
    - name: Check with pytest
      run: make VENV= check.pytest
    - name: Check with coverage
      run: make VENV= check.coverage
    - name: Check with pymarkdown
      run: make VENV= check.pymarkdown
