name: ProxyPatternPool Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
        - version: "pypy3.10"
          cover: 100.0
        - version: "pypy3.11"
          cover: 100.0
        - version: "3.10"
          cover: 100.0
        - version: "3.11"
          cover: 100.0
        - version: "3.12"
          cover: 100.0
        # 3.13 including nogil
        - version: "3.13"
          cover: 100.0
        - version: "3.13t"
          cover: 100.0
          env: PYTHON_GIL=0
        - version: "3.13t"
          cover: 100.0
          env: PYTHON_GIL=1
        # 3.14 including nogil
        - version: "3.14"
          cover: 100.0
        - version: "3.14t"
          cover: 96.5  # FIXME 3.14t coverage issue?!
          env: PYTHON_GIL=0
        - version: "3.14t"
          cover: 96.5  # FIXME 3.14t coverage issue?
          env: PYTHON_GIL=1
    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python.version }}
      # uses: actions/setup-python@v5
      # FIXME switch to v6 when available
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python.version }}
        allow-prereleases: true
        cache: "pip"
    # Dependencies
    - name: Install Python Dependencies
      run: make dev
    # Checks
    - name: Check with pyright
      run: make check.pyright
    # - name: Check with black
    #  run: black --check ProxyPatternPool.py
    # - name: Check with flake8
    #   run: make check.flake8
    - name: Check with ruff
      run: make check.ruff
    - name: Check with pytest
      run: make check.pytest
    - name: Check with coverage
      run: make COVER=${{ matrix.python.cover }} check.coverage
    - name: Check with pymarkdown
      run: make check.pymarkdown
